package controller;

public enum MenuCommands {
	APP_QUIT,
	SHOW_LIST_WAREHOUSES,
	SHOW_DETAIL_WAREHOUSE,
	SHOW_ADD_WAREHOUSE,
	DELETE_WAREHOUSE,
	SHOW_EDIT_WAREHOUSE,
	SHOW_LIST_PARTS,
	SHOW_DETAIL_PART,
	SHOW_EDIT_PART, 
	SHOW_ADD_PART, 
	DELETE_PART,
	SHOW_LIST_INVENTORY_ITEMS,
	SHOW_DETAIL_INVENTORY_ITEM,
	SHOW_EDIT_INVENTORY_ITEM,
	SHOW_ADD_INVENTORY_ITEM,
	DELETE_INVENTORY_ITEM, 
	USER_LOGIN,
	GENERATE_PDF, 
	GENERATE_EXCEL, 
	CREATE_FILE_VIEW
}
